name: Deploy to Server via SSH

on:
  push:
    branches:
      - main  # or 'master'

jobs:
  deploy:
    name: Deploy to Amazon Linux Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Add Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Deploy Application
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            cd /home/ec2-user/simple-gin-app

            echo "Stopping existing app (if running)..."
            pkill -f ./myapp || true

            echo "Updating source..."
            git pull origin main  # or 'master' if that's your branch

            echo "Building Go app..."
            export PATH=$PATH:/usr/local/go/bin  # Adjust if Go is installed elsewhere
            go build -o myapp main.go

            echo "Starting app in background..."
            nohup ./myapp > myapp.log 2>&1 &
          EOF
        shell: bash
